### ISSUE TITLE
run EventQueue tutorial 3, ordered queue failed

### ISSUE THREAD

**Issue by qgyhd1234** [wqking/eventpp#23]
PC： win10 64bit

我 clone 了仓库后，编译了 tutorial.exe，执行时提示产生了断言 ，dtor 是空指针

将 EventQueue tutorial 3, ordered queue 测试代码注释后，能跑完剩下的 16 个测试

![image](https://user-images.githubusercontent.com/19366952/117532996-b9efb780-b01c-11eb-9199-c6a585aaa103.png)

**Comment by wqking** [comment]
Thanks for the bug report. I've fixed it.
That bug doesn't affect the core classes, it only affects `OrderedQueueList`, because `OrderedQueueList` tried to access empty `BufferedItem` when comparing the items.
That bug only occurs in VC debug mode, it doesn't happen in release mode because by default `assert` is not in release mode.
