### ISSUE TITLE
Can you add an extra sample code for the Tutorials of EventDispatcher document

### ISSUE THREAD

**Issue by asmwarrior** [wqking/eventpp#51]
Hi, the document:

[eventpp/tutorial_eventdispatcher.md at master · wqking/eventpp](https://github.com/wqking/eventpp/blob/master/doc/tutorial_eventdispatcher.md)

Looks good!

But at the last statement:

> Remarks A common situation is an Event class is defined as the base class, all other events derive from Event, and the actual event type is a data member of Event (think QEvent in Qt). To let EventDispatcher knows how to get the event type from class Event, policies (the third template parameter) is used.

So my suggestion is that can you add another example about using the policies?

I see a similar example in this page: [eventpp/argumentadapter.md at master · wqking/eventpp](https://github.com/wqking/eventpp/blob/master/doc/argumentadapter.md)

But argument adapter is the second argument of the function `appendListener()`, while the policy is the third argument.

Thanks.

BTW: I'm not sure, I see your library is the only library which support such policy feature. I mean that for many applications, when signal(event) can have different types, and we have different kinds of callback functions, such as:

~~~~
void callback1(EventA &e);
void callback2(EventB &e);
~~~~

The need here is both the above two functions can be added to the single signal/slot dispatcher object, and once a EventA signal happens, the callback1 function will be called, and not callback2.  Once a EventB signal happens ,the callback2 function will be called, but not callbak1 function.

Generally, people don't need to use two different dispatcher objects for different event/signal classes, which make the library more flexible!

**Comment by wqking** [comment]
>> So my suggestion is that can you add another example about using the policies?

The tutorial with that remarks has already demonstrated it. :-)
But it's a good idea to put the key/mouse tutorial there as a more comprehensive example, I will do it.

>> Generally, people don't need to use two different dispatcher objects for different event/signal classes, which make the library more flexible!

You don't need to use different dispatcher objects, you only need to use one dispatcher for the base event class, then inherit all events from that base. A quick pseudo example is (same to the key/mouse example), you have,
`struct Event;`, `struct KeyEvent : Event;`, then you can have dispatcher with prototype of `void (const Event &)`, then you can dispatch `dispatcher.dispatch(KeyEvent())`. Or use `std::unique_ptr` or `std::shared_ptr` instead of reference, which should be used if you use `EventQueue`.

The feature you advised is already supported in the Heterogeneous classes. There is a section in the documents for them.
However, the heter classes are mostly for Proof of Concept purpose rather than massive usage, so it was not well maintained.
It has some disadvantage to the core classes (homogeneous classes) than,
1. The code is much more difficult to write, and the code is very complicated. Though it's not problem for the users.
2. It has slightly memory and performance overhead than core classes, though I didn't benchmark it.
3. The API interface may not be same as core classes, because some API is impossible or very difficult to implement in heter. I can't remember which function, though.

From view of architecture, I don't recommend to use the Heterogeneous classes, or the way you proposal that the callback may have different prototypes, because,
1. When you have many kinds of event types, you may quickly lose control on the large amount of event types, event classes, and event callback prototypes.
2. It's difficult to communicate with other developers. Beside documenting the event type and classes, you need to document the prototypes that you used?
3. Though we can do the Heterogeneous event system in C++, in most applications in the world the main stream is homogeneous, not only C++, but also Java, C#, etc, so we'd better keep in the main stream.
4. Same as the point 2 in the "disadvantage" list above, more flexibility means more cost. Event system is very essential in an application, so performance should be critical.

However, all above are my personal opinion. If more people/projects are interesting in heterogeneous event system, we may evolve the current implementation better.

**Comment by asmwarrior** [comment]
Hi, thanks for the response and explanation.

I just looked at the document: [eventpp/heterogeneous.md at 6e5f6ee45d6e9b1aad8d6bb533cafd1333b2a8e6 · wqking/eventpp](https://github.com/wqking/eventpp/blob/6e5f6ee45d6e9b1aad8d6bb533cafd1333b2a8e6/doc/heterogeneous.md), and as you said, the heterogeneous classes means the callback function have different prototypes, such as in the document:

~~~~
eventpp::EventDispatcher<int, void ()> dispatcher;
dispatcher.appendListener(3, []() {}); // OK
dispatcher.appendListener(3, [](std::string) {}); // wrong, can't listen for void(std::string)
~~~~

But what I need may be a little different, the callback function have some similar prototype, for example, I searched on the StackOverflow site, and this question is exact problem I have:


[c++ - Typesafe implementation of an event system - Stack Overflow](https://stackoverflow.com/questions/47485745/typesafe-implementation-of-an-event-system)

~~~~
// Create the on event functions
std::function<void(const ClickEvent &)> onClickFunction = [](const ClickEvent & event)
{
    std::cout << std::endl << "Mouse clicked at position: " << event.x << event.y;
};

std::function<void(const RenderNodeCreatedEvent &)> onRenderNodeCreatedFunction = [](const RenderNodeCreatedEvent & event)
{
    std::cout << std::endl << "Render node created with id: " << event.renderNodeId;
};

// Create the events
ClickEvent clickEvent;
clickEvent.x = 300.f;
clickEvent.y = 255.5f;

RenderNodeCreatedEvent renderNodeCreatedEvent;
renderNodeCreatedEvent.renderNodeId = 26234628374324;

// Create the event manager and subscribe the event functions
EventManager eventManager;
eventManager.Subscribe(onClickFunction);
eventManager.Subscribe(onRenderNodeCreatedFunction);

// Raise the events
eventManager.Raise(clickEvent);
eventManager.Raise(renderNodeCreatedEvent);
~~~~

You can see, the event class is the only argument for the each event handler, and either `ClickEvent` and `RenderNodeCreatedEvent` are derived from the same base class `Event`.

**Comment by wqking** [comment]
"similar prototype" is still different prototype, heterogeneous classes support your example.

**Comment by asmwarrior** [comment]
> "similar prototype" is still different prototype, heterogeneous classes support your example.

Indeed, they are different prototypes.

Meanwhile, I create a gist sample [event_system.cpp](https://gist.github.com/asmwarrior/473a4ad40bfba7a1e8eb777ed0bb7846) file in github, which I follow the way mentioned in [c++ - ECS Event/Messaging implementation - Code Review Stack Exchange](https://codereview.stackexchange.com/questions/79211/ecs-event-messaging-implementation).

The trick is the argument type is stored in the callback wrapper, once the event happens, a map(in the code, it use `std::vector<std::vector>>` is used to locate the associated callbacks and call them(a static cast is need here).

I'm really not sure how the `eventpp` library did in the heterogeneous classes.

Thanks.

**Comment by wqking** [comment]
There is no tutorial for heter classes, but you can [check the unit test](https://github.com/wqking/eventpp/blob/15d78b7bd2700ff13b596069a9e2a09ee14ad7f0/tests/unittest/test_heterdispatcher_basic.cpp#L434)  
You can replace the prototype `void (const MyEvent &)` with `const PLAYER_HIT& event`, `void (const MyEvent &, int)` with `const PLAYER_LVL_UP& event`, etc.

**Comment by asmwarrior** [comment]
Thanks for the reply.

https://github.com/wqking/eventpp/blob/15d78b7bd2700ff13b596069a9e2a09ee14ad7f0/tests/unittest/test_heterdispatcher_basic.cpp#L434-L472

Sorry, I quite understand the method:


> There is no tutorial for heter classes, but you can [check the unit test](https://github.com/wqking/eventpp/blob/15d78b7bd2700ff13b596069a9e2a09ee14ad7f0/tests/unittest/test_heterdispatcher_basic.cpp#L434) You can replace the prototype `void (const MyEvent &)` with `const PLAYER_HIT& event`, `void (const MyEvent &, int)` with `const PLAYER_LVL_UP& event`, etc. That test is to test `ArgumentPassingMode`, but you can ignore it safetly.

I can replace the the `const MyEvent &)` in the following code:

https://github.com/wqking/eventpp/blob/15d78b7bd2700ff13b596069a9e2a09ee14ad7f0/tests/unittest/test_heterdispatcher_basic.cpp#L459-L465

But How can I replace the `MyEvent` definition?

https://github.com/wqking/eventpp/blob/15d78b7bd2700ff13b596069a9e2a09ee14ad7f0/tests/unittest/test_heterdispatcher_basic.cpp#L436-L439

**Comment by wqking** [comment]
I will try to add some tutorials.

**Comment by wqking** [comment]
I added more tutorials for EventQueue. [Tutorial 4](https://github.com/wqking/eventpp/blob/master/doc/tutorial_eventqueue.md) is what you are looking for.  
I also added tutorial for HeterEventDispatcher. It's not in document, but you can [check the code](https://github.com/wqking/eventpp/blob/master/tests/tutorial/tutorial_hetereventdispatcher.cpp)

**Comment by wqking** [comment]
The tutorials are enough for demonstrating how it works. I will close this issue.

**Comment by asmwarrior** [comment]
Thanks for your tutorial!
